{% set name = "libgpg-error" %}
{% set version = "1.51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: be0f1b2db6b93eed55369cdf79f19f72750c8c7c39fc20b577e724545427e6b2

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # excellent backwards compatibility
    # https://abi-laboratory.pro/tracker/timeline/libgpg-error/
    - {{ pin_subpackage('libgpg-error') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - gettext

test:
  requires:
    # Needed to run conda inspect, esp. on osx
    - conda-bld
  commands:
    - test -f $PREFIX/lib/libgpg-error.so  # [linux]
    - conda inspect linkages {{ name }}
    - conda inspect objects {{ name }}  # [osx]

about:
  home: https://gnupg.org/software/index.html
  license: GPL-2.0
  license_family: GPL2
  summary: 'a small library that originally defined common error values for all GnuPG components'

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
