{% set name = "libgpg-error" %}
{% set version = "1.58" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: f943aea9a830a8bd938e5124b579efaece24a3225ff4c3d27611a80ce1260c27

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # excellent backwards compatibility
    # https://abi-laboratory.pro/tracker/timeline/libgpg-error/
    - {{ pin_subpackage('libgpg-error') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - pkg-config
    - gettext

test:
  requires:
    # Needed to run conda inspect, esp. on osx
    - conda-build
  commands:
    - test -f $PREFIX/lib/libgpg-error${SHLIB_EXT}
    - test -f $PREFIX/bin/gpg-error
    - test -f $PREFIX/bin/gpgrt-config
    - test -f $PREFIX/bin/yat2m
    - test -f $PREFIX/include/gpg-error.h
    - test -f $PREFIX/include/gpgrt.h
    - conda inspect linkages {{ name }}
    - conda inspect objects {{ name }}  # [osx]

about:
  home: https://gnupg.org/software/libgpg-error/index.html
  doc_url: https://gnupg.org/software/libgpg-error/index.html
  dev_url: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgpg-error.git
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING.LIB
  summary: a small library that originally defined common error values for all GnuPG components
  description: | 
    Libgpg-error is a small library that originally defined common error values for all 
    GnuPG components. Among these are GPG, GPGSM, GPGME, GPG-Agent, 
    libgcrypt, Libksba, DirMngr, Pinentry, SCdaemon.

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
