travis:
  secure:
    BINSTAR_TOKEN: ifw1+B8rEx4eq5KdirPiBZm1nYgxTWqfzVQBxScXc87+RGWwTXHJuTFeBoTxa5HUuINi6MQPlgiGXfUXsFxJcXHsGt+SO8X14U6jycijmqIcEcvDf9C2qkk1Q0LWIzOiFTsNFNCGfJ4FZCIKHd9Lkc4s23CoMfSigcnSI5vl+P5PyQwu61aR/nT1DphWIl4D02EReYddNcVmyVkapyJ5C6bCac7IqwjrlLdmiWuquVCXZQrtm6XaFdZpd+9y6baWiC1YtXiM0vuUgU6iDP9u1EgYGVpl6U1L09FdyhVVjtSfDD3CxNLVs+fd57ecpNMUPQABj8MQFgBx82q0N6eBA2LtCJAIqSmFW5nwJI+1MPY8tcpUv17DOY+HpGfVxMXMkUjNnyoHe9U6pxc7hd8m70DZjVULyX77GvrksYTk2Ihzx7CuLD/rh1OTQRQRS7IFVvdexa9vHb+Ib69ywow5d9pZYxCHoZJb0fWEBVCKASLnu8BxpjLiPCt4HuQdc2rQHWpRxN7I02EfEZTYS6Fu+oeEgLywKJhkN7RtdCSu4goIFSxkBKlXZIioTeQBfaNIX4VJOlltT3xuJATfodWrLyAoZ7/K/+/zA7OHbMXOZ/ATZ2lXVrFae6ekFmjsmwM1NFn5/y9lyPl0vmQvq55cqT/n2wLA19rkZxrwRtr865o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
